name: Deploy Docker Image

on:
  workflow_run:
    workflows: ["Build and Push Docker Image"]
    types:
    - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Pull latest code
      run: git pull origin master

    - name: Deploy Docker image
      run: |
        docker pull ${{ secrets.DOCKER_USERNAME }}/sample-nginx:latest
        docker run -d -p 80:80 ${{ secrets.DOCKER_USERNAME }}/sample-nginx:latest

